/** A single inquiry with claim-linked evidence, updated in place after source checks. */
import type { InquiryResult as Result } from "@/lib/inquiry-result";
const labels = { historical: "Historical question", interpretation: "Present-day interpretation", mixed: "History + interpretation", explanation: "Explanation" };
type Props = { question: string; result: Result; checking: boolean; busy: boolean; checked: boolean; error: string; onVerify: () => void; onFollowUp: (question: string) => void };
export function InquiryResult({ question, result, checking, busy, checked, error, onVerify, onFollowUp }: Props) {
  return <article className="inquiry-result paper-card" aria-label="Inquiry result">
    <header className="result-header"><span className="eyebrow">Your inquiry</span><h2>{question}</h2><span className="answer-badge">{labels[result.answerType]}</span></header>
    <div className="answer-grid"><section className="short-answer"><h3>The short answer</h3><p>{result.shortAnswer}</p>{result.interpretationBoundary && <aside className="boundary-note"><h4>Where interpretation begins</h4><p>{result.interpretationBoundary}</p></aside>}</section>
      {result.answerType !== "explanation" && <section className="historical-basis"><h3>What Gandhi actually said</h3>{result.historicalBasis.length ? <ul>{result.historicalBasis.map((item, index) => <li key={item.sourceId}>{item.claim} <a href={`#${item.sourceId}`} aria-label={`Read source ${index + 1}`}>[{index + 1}]</a></li>)}</ul> : <p className="muted">{checked ? "This check did not establish a source-backed historical point. The interpretation is not a recorded statement." : "No source-backed passage is attached yet. Check sources to examine the historical basis."}</p>}</section>}
    </div>
    {(result.contestedReadings.length > 0 || result.missingEvidence) && <section className="result-section debated"><h3>What is debated or incomplete here</h3>{result.contestedReadings.map((point, index) => <p key={index}>{point}</p>)}{result.missingEvidence && <p>{result.missingEvidence}</p>}</section>}
    <section className="result-section evidence-section" aria-busy={checking}><div className="section-heading"><div><h3>Sources and reasoning</h3><p className="muted">See the passage behind each historical point.</p></div><button type="button" className="secondary-button" onClick={onVerify} disabled={busy}>{checking ? "Checking sources…" : error ? "Retry source check" : checked ? "Check again" : "Check sources"}</button></div>
      {checking && <p role="status" className="progress-note">Checking relevant passages. This result will update here when the check is complete.</p>}{error && <p role="alert" className="error-note">{error}</p>}{checked && !checking && !error && <p className="check-note" role="status">Source check completed. The evidence and any remaining limits are shown below.</p>}{checked && result.verificationSummary && <p className="verification-summary">{result.verificationSummary}</p>}
      {result.sources.length ? <ol className="source-list">{result.sources.map((source, index) => <li id={source.id} key={source.id} className="source-card"><a href={source.url} target="_blank" rel="noopener noreferrer">{index + 1}. {source.title} <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a><p><span className="source-label">Supports:</span> {source.claimSupported}</p><details><summary>Read the supporting passage</summary><blockquote>{source.passage}</blockquote></details></li>)}</ol> : !checking && <p className="muted">No source links are attached to this result. That is not proof that no record exists.</p>}
    </section>
    {result.suggestedFollowUps.length > 0 && <section className="result-section follow-ups"><h3>Explore further</h3><div className="follow-up-list">{result.suggestedFollowUps.map(question => <button type="button" key={question} onClick={() => onFollowUp(question)}>{question} <span aria-hidden="true">↗</span></button>)}</div></section>}
  </article>;
}
