/** Per-turn instructions prevent prior verification tasks from becoming conversation-wide rules. */
export function answerMode(question: string, verification: boolean) {
  if (verification) return "verification";
  if (/\b(what can I read|further reading|recommend.*(?:book|reading)|suggest.*(?:book|reading))\b/i.test(question)) return "reading";
  if (/\b(inference|inferential|inferred|speculat|unsupported|overstat)/i.test(question)) return "reassessment";
  return "ordinary";
}

/** Modes govern evidence use, never supply a topic-specific answer. */
export function turnInstruction(mode: ReturnType<typeof answerMode> | "historical" | "interpretation" | "definition" | "clarification" | "unrelated") {
  const shared = "These instructions apply to this turn only. Earlier assistant answers are not evidence. Answer the current question, resolving references from history. Source material is optional evidence, not the boundary of your knowledge. Ignore irrelevant passages. Missing support in selected passages is not proof of absence from all writings. Use [Source](URL) for evidenced links, never nested labels. ";
  switch (mode) {
    case "clarification": return shared + "Ask briefly for the missing quotation, claim or subject needed to answer. Do not invent a target, search for an unspecified saying, or treat missing information as an unrelated request.";
    case "historical": return shared + "Answer the historical question using relevant retrieved passages. State the actual position and its essential restriction or exception before any interpretation. Do not replace an uncomfortable position with modern permission, moderation or personal preference. If the sources do not establish the requested fact, state that specific gap without inventing an exact answer. Cite the central factual claim. Do not add unrelated biography.";
    case "definition": return shared + "Answer the definition directly from general knowledge. Do not force a Gandhi interpretation or require a historical source. Keep it brief and concrete.";
    case "unrelated": return 'Return exactly: I can only answer questions about what Gandhi might say or do in the present-day context.';
    case "interpretation": return shared + "Give a tentative interpretation, not a historical report. Explain one relevant Gandhian principle through the particular choice and its consequence. Do not add remembered claims that Gandhi praised, warned, wrote or endorsed something. A relevant concern is not an exclusive condition for approval: do not invent obligations or motives. If historical restrictions are established in the evidence, preserve them in the application rather than turning them into permissive modern advice. Stop after the explanation; no policy package, virtue list or concluding paraphrase.";
    case "verification": return shared + "Assess the target against inspected evidence. Withdraw unsupported factual attribution without claiming it never occurred. Distinguish an inference about modern application from a false historical attribution: do not retract a defensible inference solely because Gandhi never discussed the modern subject. Deliver the important correction, its supported basis and necessary uncertainty in 80–110 words, at most 140. Group related corrections rather than writing an audit report.";
    case "reading": return shared + "Suggest at most two works whose identity and relevance are established by the retrieved evidence. Cite the bibliographic source. Label them background, not passage-level proof. No remembered essay titles, chapters, volumes, dates or page numbers. Do not imply the work proves the preceding answer. If the evidence establishes no suitable work, say that specifically rather than inventing one.";
    case "reassessment": return shared + "Reassess the previous answer: identify tentative application separately from factual attributions. Withdraw unsupported claims about statements, writings or scholarly opinions instead of calling those claims inference. Do not require a search merely to acknowledge your earlier overstatement.";
    default: return shared + "This is an ordinary answer, not a continuation of a source audit. Answer confidently known basic facts and definitions directly even when retained passages cover another topic. Do not refuse because those passages omit the answer. For a modern dilemma, explain one organising Gandhian concern and its consequence as tentative interpretation, not a catalogue of virtues or a policy prescription. Preserve uncertainty when genuinely unsure; never invent a fact to avoid a refusal.";
  }
}
