import { expect, test } from "bun:test";
import { evidenceCatalog, parseResult, resultFormat } from "./structured-answer";
const base = { answerType: "interpretation", shortAnswer: "A tentative application.", historicalBasis: [], interpretationBoundary: "This is an interpretation, not recorded speech.", contestedReadings: [], missingEvidence: "", suggestedFollowUps: [], verificationSummary: "" };
const evidence = evidenceCatalog(JSON.stringify({ excerpts: [{ sourceUrl: "https://example.org/document", sourceTitle: "Document", text: "The complete source passage says this." }] }));
test("strict schema requires every field and rejects additional properties", () => {
  expect(resultFormat.json_schema.strict).toBe(true);
  expect(resultFormat.json_schema.schema.additionalProperties).toBe(false);
  expect(resultFormat.json_schema.schema.required.length).toBe(8);
});
test("valid unsupported interpretation remains explicit and has no fake historical section", () => {
  expect(parseResult(JSON.stringify(base), []).sources).toEqual([]);
});
test("source metadata is resolved from the catalog, never generated by the answer", () => {
  const result = parseResult(JSON.stringify({ ...base, historicalBasis: [{ claim: "A supported claim.", evidenceId: "e1", supportingQuote: "The complete source passage says this." }] }), evidence);
  expect(result.sources[0].url).toBe("https://example.org/document");
  expect(result.sources[0].title).toBe("Document");
  expect(result.historicalBasis[0].sourceId).toBe(result.sources[0].id);
});
test("invalid structure, unsupported IDs and altered quotations are refused", () => {
  for (const value of [null, { ...base, answerType: "guess" }, { ...base, interpretationBoundary: "" }, { ...base, shortAnswer: Array(141).fill("word").join(" ") }, { ...base, historicalBasis: [{ claim: "Claim", evidenceId: "invented", supportingQuote: "The complete source passage says this." }] }, { ...base, historicalBasis: [{ claim: "Claim", evidenceId: "e1", supportingQuote: "An invented passage that was never supplied." }] }]) expect(() => parseResult(JSON.stringify(value), evidence)).toThrow();
});
test("malformed and non-web source URLs never become links", () => {
  const catalog = evidenceCatalog(JSON.stringify({ excerpts: ["javascript:alert(1)", "https://", "https://name:password@example.org"].map(sourceUrl => ({ sourceUrl, text: "Source passage" })) }));
  expect(catalog).toEqual([]);
});
