import { expect, test } from "bun:test";
import { evidenceCatalog, parseResult, resultFormat } from "./structured-answer";
const base = { answerType: "interpretation", shortAnswer: "A tentative application.", historicalBasis: [], interpretationBoundary: "This is an interpretation, not recorded speech.", contestedReadings: [], missingEvidence: "", suggestedFollowUps: [], verificationSummary: "" };
const evidence = evidenceCatalog(JSON.stringify({ excerpts: [{ sourceUrl: "https://example.org/document", sourceTitle: "Document", text: "The complete source passage says this." }] }));
test("strict schema requires every field and rejects additional properties", () => {
  expect(resultFormat.json_schema.strict).toBe(true);
  expect(resultFormat.json_schema.schema.additionalProperties).toBe(false);
  expect(resultFormat.json_schema.schema.required.length).toBe(8);
});
test("valid unsupported interpretation remains explicit and has no fake historical section", () => {
  expect(parseResult(JSON.stringify(base), []).sources).toEqual([]);
});
test("source metadata is resolved from the catalog, never generated by the answer", () => {
  const result = parseResult(JSON.stringify({ ...base, historicalBasis: [{ claim: "A supported claim.", evidenceId: "e1", supportingQuote: "The complete source passage says this." }] }), evidence);
  expect(result.sources[0].url).toBe("https://example.org/document");
  expect(result.sources[0].title).toBe("Document");
  expect(result.historicalBasis[0].sourceId).toBe(result.sources[0].id);
});
test("invalid structure and unsupported IDs are refused", () => {
  for (const value of [null, { ...base, answerType: "guess" }, { ...base, interpretationBoundary: "" }, { ...base, shortAnswer: Array(141).fill("word").join(" ") }, { ...base, historicalBasis: [{ claim: "Claim", evidenceId: "invented" }] }]) expect(() => parseResult(JSON.stringify(value), evidence)).toThrow();
});
test("displayed passage comes from the server, not a model quotation", () => {
  const result = parseResult(JSON.stringify({ ...base, historicalBasis: [{ claim: "Claim", evidenceId: "e1", supportingQuote: "Invented text is ignored" }] }), evidence);
  expect(result.sources[0].passage).toBe(evidence[0].text);
});
test("malformed and non-web source URLs never become links", () => {
  const catalog = evidenceCatalog(JSON.stringify({ excerpts: ["javascript:alert(1)", "https://", "https://name:password@example.org"].map(sourceUrl => ({ sourceUrl, text: "Source passage" })) }));
  expect(catalog).toEqual([]);
});
test("source titles and excerpts exclude browser viewing-line metadata", () => {
  const catalog = evidenceCatalog(JSON.stringify({ excerpts: [{ sourceUrl: "https://example.org/document", sourceTitle: "example.org - viewing lines [0 - 40] of 40", text: "L0: \nL1: URL: https://example.org/document\nL2: The documented title\nL3: \nL4: Original source words." }] }));
  expect(catalog[0].title).toBe("The documented title");
  const result = parseResult(JSON.stringify({ ...base, historicalBasis: [{ claim: "Claim", evidenceId: "e1" }] }), catalog);
  expect(result.sources[0].passage).toContain("Original source words.");
  expect(result.sources[0].passage).not.toMatch(/L\d+:/);
});
test("public correction prose resolves evidence identifiers to real titles", () => {
  const result = parseResult(JSON.stringify({ ...base, verificationSummary: "e1 supports the historical point." }), evidence);
  expect(result.verificationSummary).toBe("“Document” supports the historical point.");
  expect(() => parseResult(JSON.stringify({ ...base, verificationSummary: "e99 supports this." }), evidence)).toThrow();
});
